"""
Django settings for trial_universityofbigdata project.

Generated by 'django-admin startproject' using Django 4.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path
from django.utils.translation import gettext_lazy as _
from .settings_local import *
from .settings_social import *
from .settings_sw import *

import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/


# SECURITY WARNING: don't run with debug turned on in production!
# from .settings_sw import *


# Application definition
AUTH_USER_MODEL = 'accounts.User'

INSTALLED_APPS = [
    'accounts.apps.AccountsConfig', # ユーザー/チーム管理追加
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'universityofbigdata.apps.UniversityofbigdataConfig',# 追加
    'django_bootstrap5',
    'django_pandas',  # 設定
    'social_django',  # ソーシャル認証用追加
    'django_cleanup.apps.CleanupConfig',  # django-cleanup
    'competitions.apps.CompetitionsConfig', # コンペ用追加
    'discussion.apps.DiscussionConfig', # 議論
    'django_apscheduler', # 定期実行処理(コンペの更新など)
    'userlog.apps.UserlogConfig',
    'management.apps.ManagementConfig',
    'authentication.apps.AuthenticationConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware', # 追加
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'social_django.middleware.SocialAuthExceptionMiddleware',  # 追加
]

ROOT_URLCONF = 'trial_universityofbigdata.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'social_django.context_processors.backends',  # 追加
                'social_django.context_processors.login_redirect', # 追加
            ],
        },
    },
]
WSGI_APPLICATION = 'trial_universityofbigdata.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'data' / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/
LANGUAGE_CODE = 'ja'  # もとの値: 'en-us'
TIME_ZONE = 'Asia/Tokyo'  # もとの値: 'UTC'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
STATIC_ROOT = os.path.join(BASE_DIR, 'data', 'static')

""" --------------追記----------------"""

# ファイル保存設定
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'data', 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# 言語変換設定
LOCALE_PATHS = [
    BASE_DIR / 'locale'
]
LANGUAGES = [
    ('ja', _('日本語')),
    ('en', _('英語')),
]

# ソーシャル認証設定
#LOGIN_URL = 'login_google' # google認証用
#LOGIN_REDIRECT_URL = 'login_required' # 認証後遷移
LOGIN_URL = 'login' # google認証用
LOGIN_REDIRECT_URL = 'signup_google'
LOGOUT_REDIRECT_URL = '/'

# logger 用設定
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },
    'formatters': {
        'django.server': {
            '()': 'django.utils.log.ServerFormatter',
            'format': '[%(server_time)s] %(message)s a',
        },
        'verbose': {
            'format': '%(levelname)s %(asctime)s %(module)s '
                      '%(message)s a'
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'filters': ['require_debug_true'],
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'django.server': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'django.server',
        },
        'mail_admins': {
            'level': 'ERROR',
            'filters': ['require_debug_false'],
            'class': 'django.utils.log.AdminEmailHandler'
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'mail_admins'],
            'level': 'INFO',
        },
        'django.server': {
            'handlers': ['django.server'],
            'level': 'INFO',
            'propagate': False,
        },
        #追加
        'competitions': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        #追加
        'discussion': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        #追加
        'accounts': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        #追加
        'universityofbigdata': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        #追加
        'trial_universityofbigdata': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    }
}

